#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmartTechAND.Resource", IsApplication=true)]

namespace SmartTechAND
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int smarttech = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001e
			public const int barChart = 2131099678;
			
			// aapt resource value: 0x7f060002
			public const int btnAnswer1Excellent = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int btnAnswer1Fair = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int btnAnswer1Good = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int btnAnswer1Poor = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int btnAnswer2Excellent = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int btnAnswer2Fair = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int btnAnswer2Good = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int btnAnswer2Poor = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int btnAnswer3Excellent = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int btnAnswer3Fair = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int btnAnswer3Good = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int btnAnswer3Poor = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int btnAnswer4Excellent = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int btnAnswer4Fair = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int btnAnswer4Good = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int btnAnswer4Poor = 2131099671;
			
			// aapt resource value: 0x7f06001d
			public const int btnResult = 2131099677;
			
			// aapt resource value: 0x7f060001
			public const int layoutAnswer1 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int layoutAnswer2 = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int layoutAnswer3 = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int layoutAnswer4 = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int layoutResult = 2131099672;
			
			// aapt resource value: 0x7f060000
			public const int txtQuestition1 = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int txtQuestition2 = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int txtQuestition3 = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int txtQuestition4 = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int txtResult1 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int txtResult2 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int txtResult3 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int txtResult4 = 2131099676;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Result = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
